### ISSUE TITLE
Write a characteristic node

### ISSUE THREAD

**Issue by moisesfa** [gtalusan/node-red-contrib-ignoble#2]
Could you explain to me how write a characteristic node works ?
The other nodes work perfectly but I can not write a characteristic. I do not know how to do it.
Thank you,

**Comment by gtalusan** [comment]
Hi @moisesfa, use an output characteristic node and set the UUID.  Be sure it's in lower case or whatever case Bleno works with your device.

I have an function node before it that looks like this:

```
msg.payload = "TESTING 123!!!";
return msg;
```

msg.payload will be written to the characteristic.

**Comment by moisesfa** [comment]
In my case:
  msg.payload = [0xA0, 0x1F];
  return msg;
I have used it to communicate with Xiaomi 4 in 1 Plant Flower Care Smart Monitor. 
Excellent, it works.
Many thanks.

**Comment by gtalusan** [comment]
Good news!  Thanks for the feedback!
