### ISSUE TITLE
speed up characteristics discovery

### ISSUE THREAD

**Issue by nepeee** [gtalusan/node-red-contrib-ignoble#3]
I wanted to control a ble light bulb using this node-red module. I put together a simple flow to test this and i found that the response of this module is extremely slow about 3-5sec even with a continuous connection. When i traced back the problem i found that delay comes from the service node because its doing a service discovery every time its write to a characteristic. I quickly added a simple cache array to store the discovered characteristic list and the delay went away.

My test code:
` 
        function ServiceNode(config) {
                RED.nodes.createNode(this, config);
                var node = this;
                var charCache = [];

                node.on('input', function(msg) {
                        if (!msg._peripheral) {
                                charCache = [];
                                node.status({ fill: "red", shape: "dot", text: "expecting peripheral in payload" });
                                return;
                        }

                        var peripheral = noble._peripherals[msg._peripheral];
                        if (!peripheral) {
                                charCache = [];
                                node.status({ fill: "red", shape: "dot", text: "expecting peripheral in noble" });
                                return;
                        }

                        peripheral.once('disconnect', function() {
                                charCache = [];
                                node.status({});
                        });

                        if (charCache.length>0) {
                                for (var i = 0; i < charCache.length; i++) {
                                        var m = Object.assign({}, msg);
                                        m._service = charCache[i];
                                        node.send(m);
                                }
                                return;
                        }

                        async.eachSeries(peripheral.services, function(service, done) {
                                service.discoverCharacteristics([], function(error, characteristics) {
                                        if (error) {
                                                node.log(error);
                                        }
                                        var m = Object.assign({}, msg);
                                        m._service = service.uuid;
                                        node.send(m);
                                        charCache.push(service.uuid);
                                        setTimeout(done, 500);
                                });
                        });
                });
        }
`

I think this module at least need some caching like in my example or a better solution is to completely remove this unnecessary service node and put this code directly in the peripheral node.

**Comment by gtalusan** [comment]
The noble instance is global to the module and that should cache the services already.  You could just use the service node once in your application lifecycle, and then hardcode the _service parameter in the msg payload to your characteristic.

**Comment by nepeee** [comment]
I tried it and its ok, thanks!
Basically i routed the msg to the service node when the "connection msg" is received and added the _service to the other msgs as you suggested.

Why is this better then doing the service discovery directly in the peripheral node after the connection is made ? What is the benefits of a separate service node ?

This stuff is not so straightforward for the new module users :)

**Comment by gtalusan** [comment]
You just proved the benefit of the service node.  You used it to prime a cache.  QED.

**Comment by nepeee** [comment]
I tested it in the previous days, work like a charm, thanks!
